version: "3.7"

volumes:
    postgres-data:
    redis-data:
    geoserver-data:

networks:
    backend:

services:
    proxy:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - backend

    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - backend

    postgres:
        image: postgis/postgis:15-3.3
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: admin
            POSTGRES_DB: ev
            PGDATA: /var/lib/postgresql/data
        networks:
            - backend
